### PR TITLE
Perma clone

### PR DESCRIPTION
**Pull request by hamdiheb**
We've been working on Parma.cc website clone using responsive design for Project 2: Building with Responsive Design - Milestone 1
This branch in the repository includes the next files:

- _index.html_
- _css/index.css_
- _img folder with all images used for Parma website clone._
- _linters.yml_
- _stylelintrcs.json_
- _.hintrc_
- _README.md_
- _Project license file._

Finally, we've deployed this repository to GitHub pages.

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Invalid Submission :x: :disappointed: :stop_sign: 
## Hello @hamdiheb  and @DanteAlonsoHT   :handshake: :handshake: :handshake: 

Thank you for submitting a code review request. And congratulations on that you have completed this milestone, however you code review request is marked as invalid because of the  following reasons:

- [x] The submitted pull request lacks a short description

Fix all of the aforementioned issues and then request a review

Happy coding!!!
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by e71az — CHANGES_REQUESTED** [review]
## Status:  Changes Required ♻️

Hello @hamdiheb and @DanteAlonsoHT,

Remember to have the main branch empty, there should be no code in it until your pull request gets approved by a TSE.

Great project, it was a really strong submission but there are some things that need fixing before it can be approved:

## In the mobile view:

- [x] The yellow section has big top and bottom padding (the yellow banner should appear also in the mobile view, currently it is appearing in the tablet and desktop views only). 
- [ ] You can fix the padding by replacing the margin-top: 20px that you currently have for that element with padding-top: 20px.

## In the tablet view:

- [ ] The yellow section has smaller top and bottom padding.

##  Highlights (top 3 articles):

* [ ] The title of each article is a header (`hx` tag) and has a link (`a` tag) (currently you are using p tags and they have no links).

###  Tablet view:

- [ ]  Add some margin on the left of this elements to avoid this issue only seen in the tablet mode: 

image

### Desktop view:

* [ ] The TWN logo appears over the first article, at the top left corner (currently it disappears).
* [ ] There is a red overlay with a gradient in the top half of the first article.
* [ ] The date appears over the first article, at the top right corner.

## Latest Funding section

### All screen sizes: 

* [ ] The title of the section is a header (`hx` tag) and has a link (`a` tag) (you missed adding the href property to it and using an h1/h2/h3 tag)

* [ ] The nav menu (See more, Get updates, etc.) are grouped in a `nav` tag and each one has links (`a` tag) (you missed wrapping them in a nav tag)

Each article has:

* [ ] Its own title (`hx` tag) and has a link (`a` tag) (you missed the a tag with an href)
* [ ] Two categories items, with a link (`a` tag) (again, a tag with href)
* [ ] A text excerpt at the bottom, that also has a link (`a` tag) (missing the href property)
 
### Tablet:

* [ ] The nav menu is below the main title, and the options are aligned in a row, separated by |

### Desktop:

* [ ] The nav menu is to the left of the main title, and the options are aligned in a row, separated by |


### Footer:

* [ ] It contains social media icons centered in a `nav` tag, each of them with a link (`a` tag)
* [ ] Below the social media menu, there is another menu also centered, with a `nav` tag and each option with a link (`a` tag) (missing to wrap them in a nav tag instead of a p tag)
* [ ] At the bottom, there is a copyright paragraph with the TNW logo on the left (you used text instead of the TNW logo)

## [OPTIONAL]:

- [ ] Fix this overlapping between the images:

image

Please correct all the mentioned changes and request another code review, happy coding!

**Review by sinansevgi — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 
-----

Hello team,
I can see that you have implemented almost all the changes requested by the previous TSE.  
But still, As the previous TSE pointed out you have to fix below issue :

- [ ] The [TNW logo](https://imgur.com/rd8YFYT) appears over the first article, at the top left corner (currently it disappears).
This issue still exists please check [this screenshot](https://imgur.com/ccrD7pA)

-----
## [Optional]

- Top blue section (Perma.css Record) is not a part of the project. It is the addition of archiving website. You can remove it.
- Your text and images overflowing on tablet and mobile view. Since this project focuses on the responsive design you should give extra attention to these kinds of issues.
- You can easily set a z-index to preventing images from going over the navbar.
-----

"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 1 code review left for this project. If you think that the code review was not fair, [you can request a second-opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s). "

-----
You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

**Comment by hamdiheb** [comment]
> # Status: Changes Required 
> Hello team,
> I can see that you have implemented almost all the changes requested by the previous TSE.
> But still, As the previous TSE pointed out you have to fix below issue :
> 
> * [ ]  The [TNW logo](https://imgur.com/rd8YFYT) appears over the first article, at the top left corner (currently it disappears).
>   This issue still exists please check [this screenshot](https://imgur.com/ccrD7pA)
> 
> ## [Optional]
> * Top blue section (Perma.css Record) is not a part of the project. It is the addition of archiving website. You can remove it.
> * Your text and images overflowing on tablet and mobile view. Since this project focuses on the responsive design you should give extra attention to these kinds of issues.
> * You can easily set a z-index to preventing images from going over the navbar.
> 
> "As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 1 code review left for this project. If you think that the code review was not fair, [you can request a second-opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s). "
> 
> You can reply to this conversation if you have any questions or need elaboration. 
> Sinan Sevgi

Hello Sinan 
Can you please send us a screenshot of this issue ( The TNW logo appears over the first article, at the top left corner (currently it disappears).

**Comment by sinansevgi** [comment]
Screenshots already included. 
This is the original https://imgur.com/rd8YFYT
This is yours
https://m.imgur.com/ccrD7pA

Your version doesn't have white TNW logo

**Comment by hamdiheb** [comment]
> Screenshots already included.
> This is the original https://imgur.com/rd8YFYT
> This is yours
> https://m.imgur.com/ccrD7pA
> 
> Your version doesn't have white TNW logo

Now i understand , thank you so much

**Review by voscarmv — APPROVED** [review]
# Project status: Approved 💯 ✨ 😎 👍 

- Excellent job addressing the issues raised by the previous TSE.

### You may merge this branch and move forward ⛙🛣️ 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
